# Generated by Django 6.1.1 on 2026-09-15 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=150)),
                ('last_name', models.CharField(blank=True, default='', max_length=150)),
                ('pass_word', models.CharField(help_text='Salted SHA-256 hash string (<hash>:<salt>)', max_length=255)),
                ('account_type', models.CharField(choices=[('SuperAdmin', 'SuperAdmin'), ('Admin', 'Admin'), ('XLSXAdmin', 'XLSX Admin'), ('Vendor', 'Vendor')], default='Admin', max_length=50)),
                ('status', models.BooleanField(default=True, help_text='Active/inactive toggle')),
                ('session_version', models.PositiveIntegerField(default=1, help_text='Incrementing integer used to invalidate active sessions during password reset')),
                ('web_is_active', models.CharField(default='live', help_text='Controls global site maintenance state', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Admin Detail',
                'verbose_name_plural': 'Admin Details',
                'db_table': 'admin_details',
            },
        ),
        migrations.CreateModel(
            name='AdminPasswordResetOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_otps', to='AdminApp.admindetails')),
            ],
            options={
                'verbose_name': 'Admin Password Reset OTP',
                'verbose_name_plural': 'Admin Password Reset OTPs',
                'db_table': 'admin_password_reset_otp',
            },
        ),
    ]
