# Generated by Django 6.1.1 on 2026-09-15 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admindetails',
            name='account_type',
            field=models.CharField(choices=[('SuperAdmin', 'SuperAdmin'), ('Admin', 'Admin'), ('XLSXAdmin', 'XLSX Admin'), ('Vendor', 'Vendor')], db_index=True, default='Admin', max_length=50),
        ),
        migrations.AlterField(
            model_name='admindetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='admindetails',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='admindetails',
            name='status',
            field=models.BooleanField(db_index=True, default=True, help_text='Active/inactive toggle'),
        ),
        migrations.AlterField(
            model_name='admindetails',
            name='username',
            field=models.CharField(db_index=True, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='adminpasswordresetotp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='adminpasswordresetotp',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='adminpasswordresetotp',
            name='is_used',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='admindetails',
            index=models.Index(fields=['email', 'status'], name='idx_admin_email_status'),
        ),
        migrations.AddIndex(
            model_name='admindetails',
            index=models.Index(fields=['account_type', 'status'], name='idx_admin_role_status'),
        ),
        migrations.AddIndex(
            model_name='adminpasswordresetotp',
            index=models.Index(fields=['admin', 'is_used', 'created_at'], name='idx_otp_validation'),
        ),
        migrations.AddIndex(
            model_name='adminpasswordresetotp',
            index=models.Index(fields=['email', 'is_used'], name='idx_otp_email_used'),
        ),
    ]
