# Generated by Django 6.1.1 on 2026-09-15 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_alter_admindetails_account_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('category', models.CharField(choices=[('General', 'General'), ('Policy', 'Policy & Legal'), ('Information', 'Information & About'), ('Help', 'Help & Support'), ('Custom', 'Custom Landing')], db_index=True, default='General', max_length=100)),
                ('content', models.TextField(blank=True, default='', help_text='Rich HTML / Markdown page content')),
                ('meta_title', models.CharField(blank=True, default='', max_length=255)),
                ('meta_description', models.TextField(blank=True, default='')),
                ('meta_keywords', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], db_index=True, default='published', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('show_in_header', models.BooleanField(default=False)),
                ('show_in_footer', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pages', to='AdminApp.admindetails')),
            ],
            options={
                'verbose_name': 'Content Page',
                'verbose_name_plural': 'Content Pages',
                'db_table': 'content_pages',
                'ordering': ['sort_order', '-updated_at'],
                'indexes': [models.Index(fields=['slug', 'status'], name='idx_page_slug_status'), models.Index(fields=['category', 'status'], name='idx_page_cat_status')],
            },
        ),
    ]
