# Generated by Django 6.1.1 on 2026-09-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0003_contentpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpage',
            name='canonical_url',
            field=models.CharField(blank=True, default='', help_text='Canonical URL tag', max_length=500),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='focus_keyphrase',
            field=models.CharField(blank=True, default='', help_text='Main target search keyword', max_length=255),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='og_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='og_image',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='og_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='robots_advanced',
            field=models.CharField(blank=True, default='', help_text='e.g. noarchive, nosnippet, noimageindex', max_length=100),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='robots_follow',
            field=models.CharField(choices=[('follow', 'Follow'), ('nofollow', 'Nofollow')], default='follow', max_length=20),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='robots_index',
            field=models.CharField(choices=[('index', 'Index'), ('noindex', 'Noindex')], default='index', max_length=20),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='schema_type',
            field=models.CharField(default='WebPage', max_length=100),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='structured_data',
            field=models.TextField(blank=True, default='', help_text='Custom JSON-LD schema or custom meta tags'),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='twitter_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='twitter_image',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='twitter_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
