# Generated by Django 6.1.1 on 2026-09-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0004_contentpage_canonical_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpage',
            name='components',
            field=models.JSONField(blank=True, default=list, help_text='Structured dynamic component blocks (Strapi-style Dynamic Zone / Meta Boxes)'),
        ),
        migrations.AlterField(
            model_name='contentpage',
            name='content',
            field=models.TextField(blank=True, default='', help_text='Fallback HTML / Markdown page content'),
        ),
    ]
