# Generated by Django 6.1.1 on 2026-09-15 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0005_contentpage_components_alter_contentpage_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-friendly component title e.g. Hero Banner', max_length=150)),
                ('key', models.SlugField(help_text='Unique identifier e.g. hero_banner', max_length=150, unique=True)),
                ('category', models.CharField(blank=True, default='General', help_text='Category/grouping', max_length=100)),
                ('icon', models.CharField(blank=True, default='bi-puzzle', help_text='Bootstrap icon class e.g. bi-stars', max_length=100)),
                ('description', models.TextField(blank=True, default='', help_text='Short description of what this component is used for')),
                ('fields_schema', models.JSONField(blank=True, default=list, help_text='JSON schema of input fields')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_components', to='AdminApp.admindetails')),
            ],
            options={
                'verbose_name': 'Component Definition',
                'verbose_name_plural': 'Component Definitions',
                'db_table': 'component_definitions',
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['key', 'is_active'], name='idx_comp_key_active'), models.Index(fields=['category', 'is_active'], name='idx_comp_cat_active')],
            },
        ),
    ]
