# Generated by Django 6.1.1 on 2026-09-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0006_componentdefinition'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotBatchEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_id', models.CharField(db_index=True, editable=False, max_length=30, unique=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='lot_enquiries/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], db_index=True, default='pending', max_length=20)),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='Flexible storage for extra lot fields')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lot Batch Enquiry',
                'verbose_name_plural': 'Lot Batch Enquiries',
                'db_table': 'lot_batch_enquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SellerProductEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(db_index=True, editable=False, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], db_index=True, default='pending', max_length=20)),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='Flexible storage for extra product fields')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Seller Product Enquiry',
                'verbose_name_plural': 'Seller Product Enquiries',
                'db_table': 'seller_product_enquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
