# Generated by Django 6.1.1 on 2026-09-15 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0007_lotbatchenquiry_sellerproductenquiry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lotbatchenquiry',
            old_name='lot_id',
            new_name='batch_id',
        ),
    ]
