# Generated by Django 6.1.1 on 2026-09-15 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0008_rename_lot_id_lotbatchenquiry_batch_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(db_index=True, editable=False, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], db_index=True, default='pending', max_length=20)),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='Flexible storage for individual lot fields')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='AdminApp.lotbatchenquiry')),
            ],
            options={
                'verbose_name': 'Lot Product',
                'verbose_name_plural': 'Lot Products',
                'db_table': 'lot_products',
                'ordering': ['-created_at'],
            },
        ),
    ]
