# Generated by Django 6.1.1 on 2026-09-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0009_lotproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lotbatchenquiry',
            old_name='status',
            new_name='enquiry_status',
        ),
        migrations.RenameField(
            model_name='sellerproductenquiry',
            old_name='status',
            new_name='enquiry_status',
        ),
        migrations.RemoveField(
            model_name='lotproduct',
            name='status',
        ),
        migrations.AddField(
            model_name='lotbatchenquiry',
            name='active_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='sellerproductenquiry',
            name='active_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=20),
        ),
    ]
