# Generated by Django 6.1.1 on 2026-09-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0010_rename_status_lotbatchenquiry_enquiry_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotbatchenquiry',
            name='active_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='inactive', max_length=20),
        ),
        migrations.AlterField(
            model_name='sellerproductenquiry',
            name='active_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='inactive', max_length=20),
        ),
    ]
