# Generated by Django 6.1.1 on 2026-09-18 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0014_systemsettings_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admindetails',
            name='account_type',
            field=models.CharField(choices=[('SuperAdmin', 'SuperAdmin'), ('Admin', 'Admin'), ('XLSXAdmin', 'XLSX Admin')], db_index=True, default='Admin', max_length=50),
        ),
        migrations.CreateModel(
            name='VendorDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=150, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=150)),
                ('last_name', models.CharField(blank=True, default='', max_length=150)),
                ('pass_word', models.CharField(help_text='Salted SHA-256 hash string (<hash>:<salt>)', max_length=255)),
                ('status', models.BooleanField(db_index=True, default=True, help_text='Active/inactive toggle')),
                ('session_version', models.PositiveIntegerField(default=1, help_text='Incrementing integer used to invalidate active sessions during password reset')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vendor Detail',
                'verbose_name_plural': 'Vendor Details',
                'db_table': 'vendor_details',
                'indexes': [models.Index(fields=['email', 'status'], name='idx_vendor_email_status')],
            },
        ),
        migrations.AddField(
            model_name='lotbatchenquiry',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_lots', to='AdminApp.vendordetails'),
        ),
    ]
