# Generated by Django 6.1.1 on 2026-09-18 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0018_product_enquiry_status_alter_product_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendordetails',
            name='business_location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='vendordetails',
            name='category_interested',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='vendordetails',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='vendordetails',
            name='user_type',
            field=models.CharField(choices=[('BUYER', 'Buyer'), ('SELLER', 'Seller'), ('BOTH', 'Both')], default='BUYER', max_length=20),
        ),
        migrations.AlterField(
            model_name='vendordetails',
            name='pass_word',
            field=models.CharField(blank=True, help_text='Salted SHA-256 hash string (<hash>:<salt>)', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='VendorOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_used', models.BooleanField(db_index=True, default=False)),
                ('registration_data', models.JSONField(blank=True, null=True)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_otps', to='AdminApp.vendordetails')),
            ],
            options={
                'verbose_name': 'Vendor OTP',
                'verbose_name_plural': 'Vendor OTPs',
                'db_table': 'vendor_otps',
                'ordering': ['-created_at'],
            },
        ),
    ]
