# Generated by Django 6.1.1 on 2026-09-18 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0019_vendor_otp_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lotproduct',
            name='batch',
        ),
        migrations.AddField(
            model_name='lotbatchenquiry',
            name='category_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='lotbatchenquiry',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='lotbatchenquiry',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='lotbatchenquiry',
            name='inventory_location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='lotbatchenquiry',
            name='reason_to_sell',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='lotbatchenquiry',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='lotbatchenquiry',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='lotproduct',
            name='condition',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='lotproduct',
            name='product_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='lotproduct',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sellerproductenquiry',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='sellerproductenquiry',
            name='category_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='sellerproductenquiry',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='sellerproductenquiry',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sellerproductenquiry',
            name='dimensions',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='sellerproductenquiry',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='sellerproductenquiry',
            name='excluded_countries',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='sellerproductenquiry',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellerproductenquiry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='enquiries/images/'),
        ),
        migrations.AddField(
            model_name='sellerproductenquiry',
            name='inventory_location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='sellerproductenquiry',
            name='manufacturing_country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='sellerproductenquiry',
            name='manufacturing_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellerproductenquiry',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='sellerproductenquiry',
            name='reason_to_sell',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sellerproductenquiry',
            name='sku',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='sellerproductenquiry',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sellerproductenquiry',
            name='third_party_certificate',
            field=models.FileField(blank=True, null=True, upload_to='enquiries/certificates/'),
        ),
        migrations.AddField(
            model_name='sellerproductenquiry',
            name='title',
            field=models.CharField(db_index=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sellerproductenquiry',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_enquiries', to='AdminApp.vendordetails'),
        ),
        migrations.AddField(
            model_name='sellerproductenquiry',
            name='warranty',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='sellerproductenquiry',
            name='raw_data',
            field=models.JSONField(blank=True, default=dict, help_text='Flexible storage for extra fields'),
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.CharField(db_index=True, editable=False, max_length=30, unique=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('inventory_location', models.CharField(blank=True, default='', max_length=255)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('reason_to_sell', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots', to='AdminApp.subcategory')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots', to='AdminApp.vendordetails')),
            ],
            options={
                'verbose_name': 'Lot',
                'verbose_name_plural': 'Lots',
                'db_table': 'lots',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='lotproduct',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='AdminApp.lot'),
        ),
    ]
