# Generated by Django 6.1.1 on 2026-09-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0020_lot_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnershipEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('business_location', models.CharField(blank=True, default='', max_length=255)),
                ('partnership_interest', models.CharField(blank=True, default='', max_length=255)),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('collaboration_details', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('REVIEWED', 'Reviewed'), ('CONTACTED', 'Contacted')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Partnership Enquiry',
                'verbose_name_plural': 'Partnership Enquiries',
                'db_table': 'partnership_enquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
