# Generated by Django 6.1.1 on 2026-09-19 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0021_partnershipenquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendordetails',
            name='account_entity_type',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('COMPANY', 'Company/Business')], default='COMPANY', max_length=20),
        ),
    ]
