# Generated by Django 6.1.1 on 2026-09-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0022_vendordetails_account_entity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='raw_data',
            field=models.JSONField(blank=True, default=dict, help_text='Flexible storage for extra lot specifications'),
        ),
    ]
