# Generated by Django 6.1.1 on 2026-09-21 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0023_lot_raw_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotproduct',
            name='enquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='AdminApp.lotbatchenquiry'),
        ),
    ]
