# Generated by Django 6.1.1 on 2026-09-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0024_lotproduct_enquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='active_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='inactive', max_length=20),
        ),
        migrations.AddField(
            model_name='lot',
            name='category_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='lot',
            name='enquiry_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='lot',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='lot_enquiries/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='lot',
            name='raw_data',
            field=models.JSONField(blank=True, default=dict, help_text='Flexible storage for extra lot specifications and product manifest'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='title',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
    ]
