# Generated by Django 6.1.1 on 2026-09-26 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0026_product_category_name_product_product_id_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='componentdefinition',
            name='idx_comp_key_active',
        ),
        migrations.RemoveIndex(
            model_name='componentdefinition',
            name='idx_comp_cat_active',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='product_name',
        ),
        migrations.DeleteModel(
            name='ComponentDefinition',
        ),
    ]
