# Generated by Django 6.1.1 on 2026-09-26 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0027_remove_componentdefinition_idx_comp_key_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_available_for_offers',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='AdminApp.subcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='AdminApp.maincategory'),
        ),
    ]
