# Generated by Django 6.1.1 on 2026-09-26 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0028_product_is_available_for_offers_product_subcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Product condition e.g. Brand New, Refurbished, Used', max_length=255),
        ),
    ]
