# Generated by Django 6.1.1 on 2026-09-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0029_product_condition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discount_price',
            new_name='previous_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='current_price',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0.0, help_text='Auto-calculated: Liquidating Price * 1.10', max_digits=12),
        ),
        migrations.AddField(
            model_name='product',
            name='liquidating_price',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
