# Generated by Django 6.1.1 on 2026-09-26 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0030_rename_discount_price_product_previous_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category_name',
        ),
    ]
