# Generated by Django 6.1.1 on 2026-09-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0031_remove_product_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.AddField(
            model_name='product',
            name='model_no',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Model No. / Part No.', max_length=255),
        ),
    ]
