# Generated by Django 6.1.1 on 2026-09-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0032_remove_product_sku_product_model_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_approved',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when product enquiry status was set to APPROVED', null=True),
        ),
    ]
