# Generated by Django 6.1.1 on 2026-09-26 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0033_product_date_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admindetails',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='admindetails',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='vendordetails',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='vendordetails',
            name='last_name',
        ),
    ]
