# Generated by Django 6.1.1 on 2026-09-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0034_remove_admindetails_first_name_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                UPDATE vendor_details 
                SET category_interested = '[]' 
                WHERE category_interested = '' OR category_interested IS NULL;
                ALTER TABLE vendor_details 
                ALTER COLUMN category_interested TYPE jsonb 
                USING CASE 
                    WHEN category_interested IS NULL OR category_interested = '' OR category_interested = '[]' THEN '[]'::jsonb
                    WHEN category_interested LIKE '[%' THEN category_interested::jsonb
                    ELSE to_jsonb(ARRAY[category_interested])
                END;
            """,
            reverse_sql="""
                ALTER TABLE vendor_details ALTER COLUMN category_interested TYPE varchar(255);
            """
        ),
        migrations.AlterField(
            model_name='vendordetails',
            name='category_interested',
            field=models.JSONField(blank=True, default=list, help_text='Interested categories (supports 1 or more categories)'),
        ),
    ]
