# Generated by Django 6.1.1 on 2026-09-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0035_alter_vendordetails_category_interested'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('blog_code', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('author', models.CharField(blank=True, default='Admin', max_length=150)),
                ('category_name', models.CharField(blank=True, db_index=True, default='General', max_length=100)),
                ('excerpt', models.TextField(blank=True, default='')),
                ('content', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('featured_image_url', models.CharField(blank=True, default='', max_length=500)),
                ('meta_title', models.CharField(blank=True, default='', max_length=255)),
                ('meta_description', models.TextField(blank=True, default='')),
                ('meta_keywords', models.CharField(blank=True, default='', max_length=255)),
                ('read_time', models.PositiveIntegerField(default=3)),
                ('total_reads', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], db_index=True, default='published', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'db_table': 'blog_posts',
                'ordering': ['-created_at'],
            },
        ),
    ]
