# Generated by Django 6.1.1 on 2026-09-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0037_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceAdjustmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(default='Admin', max_length=150)),
                ('action_type', models.CharField(max_length=50)),
                ('adjustment_method', models.CharField(blank=True, default='', max_length=50)),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('affected_products_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='Applied', max_length=20)),
                ('backup_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Price Adjustment Log',
                'verbose_name_plural': 'Price Adjustment Logs',
                'db_table': 'price_adjustment_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
