# Generated by Django 6.1.1 on 2026-09-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0038_priceadjustmentlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='is_maintenance_mode',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='maintenance_message',
            field=models.TextField(default='Website is under maintenance. Please check back later.'),
        ),
    ]
