# Generated by Django 6.1.1 on 2026-09-27 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0039_systemsettings_is_maintenance_mode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopupSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Important Admin Notification', max_length=255)),
                ('message', models.TextField(default='Welcome to Surplus Admin Portal. Please check your pending seller and lot enquiries.')),
                ('popup_type', models.CharField(default='info', max_length=50)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('delay_minutes', models.PositiveIntegerField(default=1, help_text='Minutes before re-showing popup after closing')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='popup_banners/')),
                ('banner_url', models.CharField(blank=True, default='', max_length=500)),
                ('button_label', models.CharField(blank=True, default='Got It', max_length=100)),
                ('button_link', models.CharField(blank=True, default='', max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Popup Setting',
                'verbose_name_plural': 'Popup Settings',
                'db_table': 'popup_settings',
            },
        ),
    ]
