# Generated by Django 6.1.1 on 2026-09-30 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0040_popupsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendordetails',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
