# Generated by Django 6.1.1 on 2026-09-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0041_vendordetails_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendordetails',
            name='business_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='vendordetails',
            name='business_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='vendordetails',
            name='tax_registration_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
