# Generated by Django 6.1.1 on 2026-09-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0042_vendordetails_business_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('enquiry_type', models.CharField(blank=True, default='', max_length=255)),
                ('message', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('REVIEWED', 'Reviewed'), ('CONTACTED', 'Contacted'), ('BLOCKED', 'Blocked')], default='PENDING', max_length=20)),
                ('is_blocked', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Us Enquiry',
                'verbose_name_plural': 'Contact Us Enquiries',
                'db_table': 'contact_us_enquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
