# Generated by Django 6.1.1 on 2026-09-30 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0043_contactusenquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='views_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='lot',
            name='views_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='views_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.CreateModel(
            name='PageViewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('lot', 'Lot Batch'), ('product', 'Product'), ('blog', 'Blog Post'), ('page', 'Page')], db_index=True, max_length=20)),
                ('entity_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('entity_slug', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('path', models.CharField(blank=True, db_index=True, default='', max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('referrer', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Page View Log',
                'verbose_name_plural': 'Page View Logs',
                'db_table': 'page_view_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id', 'ip_address', 'created_at'], name='idx_page_view_dedup_id'), models.Index(fields=['entity_type', 'entity_slug', 'ip_address', 'created_at'], name='idx_page_view_dedup_slug')],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsViewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('blog', 'Blog Post'), ('product', 'Product'), ('lot', 'Lot Batch'), ('page', 'Page'), ('other', 'Other')], db_index=True, default='other', max_length=50)),
                ('entity_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('entity_slug', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('path', models.CharField(blank=True, db_index=True, default='', max_length=500)),
                ('referrer', models.CharField(blank=True, default='', max_length=500)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='view_logs', to='AdminApp.vendordetails')),
            ],
            options={
                'verbose_name': 'Analytics View Log',
                'verbose_name_plural': 'Analytics View Logs',
                'db_table': 'analytics_view_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='idx_view_type_id'), models.Index(fields=['entity_type', 'entity_slug'], name='idx_view_type_slug')],
            },
        ),
    ]
