# Generated by Django 6.1.1 on 2026-09-30 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0044_blogpost_views_count_lot_views_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand_ref',
            field=models.ForeignKey(blank=True, help_text='Linked Brand model reference', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='AdminApp.brand'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('liquidating_price__gte', 0)), name='check_product_liquidating_price_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('current_price__gte', 0)), name='check_product_current_price_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('stock_quantity__gte', 0)), name='check_product_stock_quantity_gte_0'),
        ),
    ]
