# Generated by Django 6.1.1 on 2026-10-01 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0045_product_brand_ref_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction_id', models.CharField(db_index=True, max_length=30, unique=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('item_type', models.CharField(choices=[('custom', 'Custom Surplus Batch'), ('lot', 'Lot Manifest'), ('product', 'Product')], db_index=True, default='custom', max_length=30)),
                ('item_reference_id', models.CharField(blank=True, db_index=True, default='', help_text='Optional reference ID like lot_number or product_id', max_length=100)),
                ('item_metadata', models.JSONField(blank=True, default=dict, help_text='Point-in-time snapshot of item specifications, manifests, condition, and origin')),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('starting_bid', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('current_bid', models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=12)),
                ('reserve_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Confidential minimum price. If not met, auction ends as reserve_not_met', max_digits=12)),
                ('bid_increment', models.DecimalField(decimal_places=2, default=25.0, max_digits=10)),
                ('buy_now_price', models.DecimalField(blank=True, decimal_places=2, help_text='Instant buyout price if enabled', max_digits=12, null=True)),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField(db_index=True)),
                ('original_end_time', models.DateTimeField(blank=True, null=True)),
                ('auto_extend_minutes', models.PositiveIntegerField(default=3, help_text='Minutes to extend if a bid is placed in the final window')),
                ('auto_extend_threshold_seconds', models.PositiveIntegerField(default=120, help_text='Window before end_time (in seconds) that triggers auto-extension')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('live', 'Live'), ('ended', 'Ended'), ('sold', 'Sold'), ('reserve_not_met', 'Reserve Not Met'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('total_bids', models.PositiveIntegerField(db_index=True, default=0)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('winning_bid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Auction',
                'verbose_name_plural': 'Auctions',
                'db_table': 'auctions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuctionBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(db_index=True, decimal_places=2, max_digits=12)),
                ('max_proxy_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bid_type', models.CharField(choices=[('manual', 'Manual Bid'), ('proxy', 'Proxy / Auto Bid'), ('buy_now', 'Buy Now')], default='manual', max_length=20)),
                ('is_winning', models.BooleanField(db_index=True, default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Auction Bid',
                'verbose_name_plural': 'Auction Bids',
                'db_table': 'auction_bids',
                'ordering': ['-amount', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuctionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='auctions/%Y/%m/')),
                ('image_url', models.CharField(blank=True, default='', max_length=500)),
                ('is_primary', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Auction Image',
                'verbose_name_plural': 'Auction Images',
                'db_table': 'auction_images',
                'ordering': ['display_order', '-is_primary', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AuctionWatchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Auction Watchlist',
                'verbose_name_plural': 'Auction Watchlists',
                'db_table': 'auction_watchlists',
            },
        ),
        migrations.AddIndex(
            model_name='lot',
            index=models.Index(fields=['is_active', 'enquiry_status'], name='idx_lot_active_status'),
        ),
        migrations.AddIndex(
            model_name='lot',
            index=models.Index(fields=['category', 'is_active'], name='idx_lot_cat_active'),
        ),
        migrations.AddIndex(
            model_name='lot',
            index=models.Index(fields=['vendor', 'created_at'], name='idx_lot_vendor_created'),
        ),
        migrations.AddIndex(
            model_name='lotbatchenquiry',
            index=models.Index(fields=['enquiry_status', 'created_at'], name='idx_batch_enq_status'),
        ),
        migrations.AddIndex(
            model_name='lotbatchenquiry',
            index=models.Index(fields=['uploaded_by', 'created_at'], name='idx_batch_user_created'),
        ),
        migrations.AddIndex(
            model_name='lotproduct',
            index=models.Index(fields=['lot', 'created_at'], name='idx_lotprod_lot_created'),
        ),
        migrations.AddIndex(
            model_name='lotproduct',
            index=models.Index(fields=['enquiry', 'created_at'], name='idx_lotprod_enq_created'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'enquiry_status'], name='idx_prod_active_status'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active'], name='idx_prod_cat_active'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['subcategory', 'is_active'], name='idx_prod_subcat_active'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['vendor', 'created_at'], name='idx_prod_vendor_created'),
        ),
        migrations.AddIndex(
            model_name='sellerproductenquiry',
            index=models.Index(fields=['enquiry_status', 'created_at'], name='idx_seller_enq_status'),
        ),
        migrations.AddIndex(
            model_name='sellerproductenquiry',
            index=models.Index(fields=['vendor', 'created_at'], name='idx_seller_vendor_created'),
        ),
        migrations.AddField(
            model_name='auction',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auctions', to='AdminApp.maincategory'),
        ),
        migrations.AddField(
            model_name='auction',
            name='vendor',
            field=models.ForeignKey(blank=True, help_text='Seller / Consignor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auctions', to='AdminApp.vendordetails'),
        ),
        migrations.AddField(
            model_name='auction',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_auctions', to='AdminApp.vendordetails'),
        ),
        migrations.AddField(
            model_name='auctionbid',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='AdminApp.auction'),
        ),
        migrations.AddField(
            model_name='auctionbid',
            name='bidder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_bids', to='AdminApp.vendordetails'),
        ),
        migrations.AddField(
            model_name='auctionimage',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='AdminApp.auction'),
        ),
        migrations.AddField(
            model_name='auctionwatchlist',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlists', to='AdminApp.auction'),
        ),
        migrations.AddField(
            model_name='auctionwatchlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_watchlists', to='AdminApp.vendordetails'),
        ),
        migrations.AddIndex(
            model_name='auction',
            index=models.Index(fields=['status', 'start_time', 'end_time'], name='idx_auction_status_times'),
        ),
        migrations.AddIndex(
            model_name='auction',
            index=models.Index(fields=['item_type', 'item_reference_id'], name='idx_auction_item_ref'),
        ),
        migrations.AddIndex(
            model_name='auctionbid',
            index=models.Index(fields=['auction', 'amount'], name='idx_bid_auction_amount'),
        ),
        migrations.AddIndex(
            model_name='auctionbid',
            index=models.Index(fields=['bidder', 'created_at'], name='idx_bid_bidder_date'),
        ),
        migrations.AlterUniqueTogether(
            name='auctionwatchlist',
            unique_together={('auction', 'user')},
        ),
    ]
