# Generated by Django 6.1.1 on 2026-10-02 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0046_auction_auctionbid_auctionimage_auctionwatchlist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageviewlog',
            name='duration_seconds',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Time spent on page in seconds'),
        ),
        migrations.AddField(
            model_name='pageviewlog',
            name='is_stuck',
            field=models.BooleanField(db_index=True, default=False, help_text='Flagged if user stayed unusually long without converting'),
        ),
        migrations.AddField(
            model_name='pageviewlog',
            name='session_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pageviewlog',
            name='visitor_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
    ]
