# Generated by Django 6.1.1 on 2026-10-02 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0047_pageviewlog_duration_seconds_pageviewlog_is_stuck_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['-is_real_photo', '-uploaded_at'], 'verbose_name': 'Product Image', 'verbose_name_plural': 'Product Images'},
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_url',
            field=models.CharField(blank=True, default='', help_text='Direct Cloudflare S3/R2 image link', max_length=1000),
        ),
        migrations.AddField(
            model_name='productimage',
            name='is_real_photo',
            field=models.BooleanField(db_index=True, default=False, help_text='True = actual product photo taken by seller. False = stock/catalog/placeholder.'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/images/gallery/'),
        ),
    ]
