# Generated by Django 6.1.1 on 2026-10-02 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0048_alter_productimage_options_productimage_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='check_product_stock_quantity_gte_0',
        ),
        migrations.AddField(
            model_name='product',
            name='brand_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='msrp',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='MSRP / Original Retail Price', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='third_party_documents',
            field=models.CharField(blank=True, default='', help_text='Cloudflare S3 documents link', max_length=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_attachment',
            field=models.CharField(blank=True, default='', help_text='Cloudflare S3 PDF link', max_length=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='current_price',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0.0, help_text='Auto-calculated buyer price', max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='liquidating_price',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0.0, help_text='Liquidating Price per unit', max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='model_no',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Model No. / Part Number', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='third_party_certificate',
            field=models.BooleanField(db_index=True, default=False, help_text='3rd Party Certificate as boolean value'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='check_product_quantity_gte_0'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand_ref',
        ),
        migrations.RemoveField(
            model_name='product',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='inventory_location',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_available_for_offers',
        ),
        migrations.RemoveField(
            model_name='product',
            name='previous_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='raw_data',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_quantity',
        ),
    ]
