# Generated by Django 6.1.1 on 2026-10-02 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0049_remove_product_check_product_stock_quantity_gte_0_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inventory_location',
            field=models.CharField(blank=True, default='', help_text='Warehouse / stock location', max_length=255),
        ),
    ]
