# Generated by Django 6.1.1 on 2026-10-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0050_product_inventory_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Offer / discount percentage', max_digits=5),
        ),
    ]
