# Generated by Django 6.1.1 on 2026-10-02 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0051_product_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('LISTING', 'Listing'), ('RFQ', 'RFQ'), ('AUCTION', 'Auction'), ('SYSTEM', 'System'), ('ORDER', 'Order')], db_index=True, default='SYSTEM', max_length=20)),
                ('action_url', models.CharField(blank=True, default='', help_text='Frontend redirection route, e.g. /profile or /browse', max_length=500)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='AdminApp.vendordetails')),
            ],
            options={
                'verbose_name': 'Vendor Notification',
                'verbose_name_plural': 'Vendor Notifications',
                'db_table': 'vendor_notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['vendor', 'is_read'], name='idx_vnotif_v_read'), models.Index(fields=['vendor', '-created_at'], name='idx_vnotif_v_created')],
            },
        ),
    ]
