# Generated by Django 6.1.1 on 2026-10-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0052_vendornotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='best_selling_order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Order in Best Selling'),
        ),
        migrations.AddField(
            model_name='product',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='General display order'),
        ),
        migrations.AddField(
            model_name='product',
            name='featured_order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Order in Featured Deals'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_best_selling',
            field=models.BooleanField(db_index=True, default=False, help_text='Best Selling showcase'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, help_text='Featured Deal showcase'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_new_arrival',
            field=models.BooleanField(db_index=True, default=False, help_text='New Arrival showcase'),
        ),
        migrations.AddField(
            model_name='product',
            name='new_arrival_order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Order in New Arrivals'),
        ),
    ]
