# Generated by Django 6.1.1 on 2026-10-03 10:13

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0053_product_best_selling_order_product_display_order_and_more'),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='ProductEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
                ('content_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('embedded_text', models.TextField(blank=True, default='')),
                ('model_name', models.CharField(default='surplus-semantic-v1', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vector_embedding', to='AdminApp.product')),
            ],
            options={
                'verbose_name': 'Product Vector Embedding',
                'verbose_name_plural': 'Product Vector Embeddings',
                'db_table': 'product_embeddings',
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='idx_prod_embed_hnsw', opclasses=['vector_cosine_ops'])],
            },
        ),
    ]
