# Generated by Django 6.1.1 on 2026-10-05 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0054_productembedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='allow_counter_offers',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='ask_price_surplus_payout',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='category_allocations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='lot',
            name='condition',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='lot',
            name='excluded_export_countries',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='lot',
            name='inventory_stock_age',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='lot',
            name='key_brands_included',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='lot',
            name='load_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='lot',
            name='lot_size',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='lot',
            name='manifest_file_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='lot',
            name='number_of_distinct_skus',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='offer',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='lot',
            name='pallet_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='primary_unit_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='lot',
            name='product_and_warehouse_images_or_videos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='lot',
            name='sale_method',
            field=models.CharField(blank=True, default='offer', max_length=50),
        ),
        migrations.AddField(
            model_name='lot',
            name='shipping_size',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='lot',
            name='shipping_terms',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='lot',
            name='source_type',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='lot',
            name='third_party_certificate_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lot',
            name='third_party_documents',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='lot',
            name='total_est_retail_value_msrp',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='total_units_quantity',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='total_weight',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='lotbatchenquiry',
            name='allow_counter_offers',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lotbatchenquiry',
            name='ask_price_surplus_payout',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='lotbatchenquiry',
            name='category_allocations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='lotbatchenquiry',
            name='condition',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='lotbatchenquiry',
            name='excluded_export_countries',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='lotbatchenquiry',
            name='inventory_stock_age',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='lotbatchenquiry',
            name='key_brands_included',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='lotbatchenquiry',
            name='load_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='lotbatchenquiry',
            name='lot_size',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='lotbatchenquiry',
            name='manifest_file_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='lotbatchenquiry',
            name='number_of_distinct_skus',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='lotbatchenquiry',
            name='offer',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='lotbatchenquiry',
            name='pallet_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='lotbatchenquiry',
            name='primary_unit_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='lotbatchenquiry',
            name='product_and_warehouse_images_or_videos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='lotbatchenquiry',
            name='sale_method',
            field=models.CharField(blank=True, default='offer', max_length=50),
        ),
        migrations.AddField(
            model_name='lotbatchenquiry',
            name='shipping_size',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='lotbatchenquiry',
            name='shipping_terms',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='lotbatchenquiry',
            name='source_type',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='lotbatchenquiry',
            name='third_party_certificate_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lotbatchenquiry',
            name='third_party_documents',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='lotbatchenquiry',
            name='total_est_retail_value_msrp',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='lotbatchenquiry',
            name='total_units_quantity',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='lotbatchenquiry',
            name='total_weight',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='lot',
            name='currency',
            field=models.CharField(default='USD', max_length=50),
        ),
        migrations.AlterField(
            model_name='lotbatchenquiry',
            name='currency',
            field=models.CharField(default='USD', max_length=50),
        ),
    ]
