# Generated by Django 6.1.1 on 2026-10-06 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0055_lot_allow_counter_offers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lot',
            name='category_name',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='manifest_file_info',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='reason_to_sell',
        ),
        migrations.RemoveField(
            model_name='lotbatchenquiry',
            name='category_name',
        ),
        migrations.RemoveField(
            model_name='lotbatchenquiry',
            name='manifest_file_info',
        ),
        migrations.RemoveField(
            model_name='lotbatchenquiry',
            name='reason_to_sell',
        ),
        migrations.RemoveField(
            model_name='product',
            name='reason_to_sell',
        ),
        migrations.RemoveField(
            model_name='sellerproductenquiry',
            name='category_name',
        ),
        migrations.RemoveField(
            model_name='sellerproductenquiry',
            name='reason_to_sell',
        ),
    ]
