# Generated by Django 6.1.1 on 2026-10-06 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0056_remove_lot_category_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lot',
            name='product_and_warehouse_images_or_videos',
        ),
        migrations.RemoveField(
            model_name='lotbatchenquiry',
            name='product_and_warehouse_images_or_videos',
        ),
    ]
