# Generated by Django 6.1.1 on 2026-10-07 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0057_remove_lot_product_and_warehouse_images_or_videos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reason_to_sell',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sellerproductenquiry',
            name='reason_to_sell',
            field=models.TextField(blank=True, default=''),
        ),
    ]
