# Generated by Django 6.1.1 on 2026-10-07 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0058_product_reason_to_sell_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='product_images',
            field=models.JSONField(blank=True, default=list, help_text='List of Product image URLs'),
        ),
        migrations.AddField(
            model_name='lot',
            name='videos',
            field=models.JSONField(blank=True, default=list, help_text='List of Video URLs'),
        ),
        migrations.AddField(
            model_name='lot',
            name='warehouse_images',
            field=models.JSONField(blank=True, default=list, help_text='List of Warehouse image URLs'),
        ),
        migrations.AddField(
            model_name='lotbatchenquiry',
            name='product_images',
            field=models.JSONField(blank=True, default=list, help_text='List of Product image URLs'),
        ),
        migrations.AddField(
            model_name='lotbatchenquiry',
            name='videos',
            field=models.JSONField(blank=True, default=list, help_text='List of Video URLs'),
        ),
        migrations.AddField(
            model_name='lotbatchenquiry',
            name='warehouse_images',
            field=models.JSONField(blank=True, default=list, help_text='List of Warehouse image URLs'),
        ),
    ]
