# Generated by Django 6.1.1 on 2026-10-07 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0059_lot_product_images_lot_videos_lot_warehouse_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lot',
            name='product_images',
        ),
        migrations.RemoveField(
            model_name='lotbatchenquiry',
            name='product_images',
        ),
    ]
