# Generated by Django 6.1.1 on 2026-10-07 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0060_remove_lot_product_images_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='lot',
            name='idx_lot_cat_active',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='allow_counter_offers',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='category',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='videos',
        ),
    ]
