# Generated by Django 6.1.1 on 2026-10-09 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0061_remove_lot_idx_lot_cat_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='admin',
            field=models.ForeignKey(blank=True, help_text='Admin who created or submitted this product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='AdminApp.admindetails'),
        ),
    ]
