# Generated by Django 6.1.1 on 2026-10-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0062_product_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='intake_channel',
            field=models.CharField(blank=True, default='', help_text='Intake channel for assisted product submission (WhatsApp, Email, etc.)', max_length=50),
        ),
    ]
