# Generated by Django 6.1.1 on 2026-10-09 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0063_product_intake_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='admin',
            field=models.ForeignKey(blank=True, help_text='Admin who created or submitted this lot', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots', to='AdminApp.admindetails'),
        ),
        migrations.AddField(
            model_name='lot',
            name='intake_channel',
            field=models.CharField(blank=True, default='', help_text='Intake channel for assisted lot submission (WhatsApp, Email, etc.)', max_length=50),
        ),
    ]
