# Generated by Django 6.1.1 on 2026-10-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0064_lot_admin_lot_intake_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='admindetails',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
